export const queryKeys = {
  enquiries: ["enquiries"] as const,
  inbox: ["inbox"] as const,
  directory: ["directory"] as const,
  airTariffs: ["airTariffs"] as const,
  seaTariffs: ["seaTariffs"] as const,
  courierTariffs: ["courierTariffs"] as const,
  circulars: ["circulars"] as const,
  leads: ["leads"] as const,
  credit: ["credit"] as const,
  accounts: ["accounts"] as const,
  salesContacts: (accountId: string) => ["salesContacts", accountId] as const,
  salesTargets: ["salesTargets"] as const,
  salesTerritories: ["salesTerritories"] as const,
};
